services:
  # Application Server
  app-server:
    image: tomcat-base:latest
    container_name: tomcat-server
    hostname: tomcat-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - tomcat_log:/apps/tomcat/logs
volumes:
  tomcat_log:
    driver: local
