version: "3.7"
services:
  db:
    image: mysql-base:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: secret
      - MYSQL_DATABASE: demodatabase
      - MYSQL_USER: root
      - MYSQL_PASSWORD: usersecret
    volumes:
      - dbdata:/var/lib/mysql
      - dbconf:/etc/mysql/conf.d
      - dblog:/var/log/mysql
  dbadmin:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@course.org"
      PGADMIN_DEFAULT_PASSWORD: "course2019"
    depends_on:
        - db
volumes:
  dbdata:
    driver: local
  dbconf:
    driver: local
  dblog: 
    driver: local


  